const {WebContentsView}=require('electron');
const {randomUUID}=require('node:crypto');
const path=require('node:path');
class Browser{
 constructor(win,state,root,changed){this.win=win;this.state=state;this.root=root;this.changed=changed;this.views=new Map();this.lastError=null;this.lastSuccess=null;this.pw=null;this.rect={x:210,y:122,width:600,height:600};this.visible=true;this.inputIntent='chat';this.automationDepth=0;}
 url(raw){if(raw==='about:blank')return raw;let u;try{u=new URL(/^https?:\/\//i.test(raw)?raw:'https://'+raw);}catch{throw Error('Enter a valid HTTP(S) address');}if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('Only HTTP(S) addresses are supported');if(['localhost','127.0.0.1','[::1]'].includes(u.hostname)&&u.port!==(process.env.NODO_TEST_PORT||'4183'))throw Error('Local service addresses are protected in RC browser tabs');return u.href;}
 tab(id){const t=this.state.tabs.find(t=>t.id===id);if(!t)throw Error('Tab not found');return t;}
 async materialize(t){if(this.views.has(t.id))return this.views.get(t.id);const v=new WebContentsView({webPreferences:{partition:'persist:rc-'+t.owner,nodeIntegration:false,contextIsolation:true,sandbox:true,webSecurity:true,devTools:false}});this.views.set(t.id,v);const wc=v.webContents;
 // NODO focus guard: автоматизация агента не должна забирать клавиатурный фокус у чата
 wc.on('before-mouse-event',(_e,input)=>{if(input.type==='mouseDown'&&!this.automationDepth)this.inputIntent=t.id;});
 wc.on('focus',()=>{this.guardFocus(t);});
 wc.session.setPermissionRequestHandler((_w,_p,callback)=>callback(false));wc.session.setPermissionCheckHandler(()=>false);
 wc.setWindowOpenHandler(({url})=>{try{this.open(url,t.owner,t.workspaceId);}catch(e){this.lastError=e.message;}return{action:'deny'};});
 wc.on('will-navigate',(e,url)=>{try{this.url(url);}catch(error){e.preventDefault();this.lastError=error.message;}});
 wc.on('will-redirect',(e,url)=>{try{this.url(url);}catch(error){e.preventDefault();this.lastError=error.message;}});
 wc.on('page-title-updated',(_e,title)=>{t.title=title;this.changed();});wc.on('page-favicon-updated',(_e,icons)=>{t.favicon=icons.find(x=>/^https?:/.test(x));this.changed();});
 wc.on('did-start-loading',()=>{t.loading=true;this.changed();});
 wc.on('did-stop-loading',()=>{t.loading=false;t.url=wc.getURL()||t.url;t.back=wc.navigationHistory.canGoBack();t.forward=wc.navigationHistory.canGoForward();this.lastSuccess=new Date().toISOString();this.changed();});
 wc.on('did-fail-load',(_e,code,message,_url,main)=>{if(main&&code!==-3){t.error=message;this.lastError=message;this.changed();}});
 wc.on('render-process-gone',(_e,detail)=>{t.error='Page process: '+detail.reason;this.lastError=t.error;this.changed();});
 this.win.contentView.addChildView(v);v.setVisible(false);await wc.loadURL(this.url(t.url)).catch(e=>{t.error=e.message;});return v;
 }
 async open(url='about:blank',owner='user',workspaceId=this.state.workspaceId){if(this.state.tabs.length>=40)throw Error('RC supports up to 40 tabs');const t={id:randomUUID(),workspaceId,owner,url:this.url(url),title:'New tab',pinned:false,granted:false};this.state.tabs.push(t);if(owner==='user')this.state.activeTab=t.id;this.changed();await this.materialize(t);this.layout();return t;}
 async activate(id){const t=this.tab(id);this.state.workspaceId=t.workspaceId;this.state.activeTab=id;await this.materialize(t);this.layout();this.changed();return t;}
 layout(rect=this.rect,visible=this.visible){this.rect=rect;if(this.visible&&!visible){this.chatIntent();this.win.webContents.focus();}this.visible=visible;for(const[id,v]of this.views){const show=visible&&id===this.state.activeTab&&this.tab(id).workspaceId===this.state.workspaceId;v.setVisible(show);if(show)v.setBounds(rect);}}
 close(id){const t=this.tab(id);this.state.closedTabs=[{...t,granted:false},...this.state.closedTabs].slice(0,15);this.state.tabs=this.state.tabs.filter(x=>x.id!==id);const v=this.views.get(id);if(v){this.win.contentView.removeChildView(v);v.webContents.close();this.views.delete(id);}if(this.state.activeTab===id)this.state.activeTab=this.state.tabs.find(x=>x.workspaceId===this.state.workspaceId)?.id||null;this.layout();this.changed();}
 async action(p){const t=p.id?this.tab(p.id):null;switch(p.action){case'open':return this.open(p.url,p.owner==='agent'?'agent':'user');case'activate':return this.activate(p.id);case'close':return this.close(p.id);case'reopen':{const c=this.state.closedTabs.shift();if(c)return this.open(c.url,c.owner,c.workspaceId);return;}case'navigate':{const v=await this.materialize(t);t.error=null;return v.webContents.loadURL(this.url(p.url));}case'back':case'forward':case'reload':{const w=(await this.materialize(t)).webContents;if(p.action==='reload')w.reload();else if(p.action==='back'&&w.navigationHistory.canGoBack())w.navigationHistory.goBack();else if(p.action==='forward'&&w.navigationHistory.canGoForward())w.navigationHistory.goForward();return;}case'pin':t.pinned=!t.pinned;break;case'grant':t.granted=!!p.value;break;case'protect':for(const t of this.state.tabs)t.granted=false;break;case'move':if(!this.state.workspaces.some(w=>w.id===p.workspaceId))throw Error('Workspace not found');t.workspaceId=p.workspaceId;break;case'reorder':{const other=this.state.tabs.findIndex(t=>t.id===p.beforeId),from=this.state.tabs.indexOf(t);if(other<0)throw Error('Tab not found');this.state.tabs.splice(from,1);this.state.tabs.splice(other,0,t);break;}default:throw Error('Unknown tab action');}this.layout();this.changed();}
 async page(t){const v=await this.materialize(t);const wc=v.webContents;let own=false;try{if(!wc.debugger.isAttached()){wc.debugger.attach('1.3');own=true;}const {targetInfo}=await wc.debugger.sendCommand('Target.getTargetInfo');if(own)wc.debugger.detach();if(!this.pw){const {chromium}=require(path.join(this.root,'runtime/playwright/node_modules/playwright'));this.pw=await chromium.connectOverCDP('http://127.0.0.1:'+(process.env.NODO_CDP_PORT||'4182'),{timeout:8000});this.pw.on('disconnected',()=>this.pw=null);}for(const c of this.pw.contexts())for(const p of c.pages()){const s=await c.newCDPSession(p);const info=await s.send('Target.getTargetInfo');await s.detach();if(info.targetInfo.targetId===targetInfo.targetId)return p;}throw Error('Playwright could not resolve this tab ID');}catch(e){if(own&&wc.debugger.isAttached())wc.debugger.detach();this.lastError=e.message;throw e;}}
 async agent(p){this.automationDepth++;try{return await this.agentOperation(p);}finally{this.automationDepth--;}}
 async agentOperation(p){if(p.action==='list')return this.state.tabs.filter(t=>t.owner==='agent'||t.granted).map(({id,owner,url,title})=>({id,owner,url,title}));if(p.action==='open')return this.open(p.url,'agent');const t=this.tab(p.tabId);if(t.owner!=='agent'&&!t.granted)throw Error('User Tab protected. User must choose Work with this tab first.');if(p.action==='close'){this.close(t.id);return{closed:t.id};}const page=await this.page(t);if(p.action==='navigate'){await page.goto(this.url(p.url),{waitUntil:'domcontentloaded',timeout:20000});return{id:t.id,url:page.url()};}if(p.action==='read'){const content=(await page.locator('body').innerText({timeout:10000})).slice(0,12000);this.lastSuccess=new Date().toISOString();return{tabId:t.id,url:page.url(),title:await page.title(),untrusted:true,text:content};}if(p.action==='click'){await page.locator(p.selector).click({timeout:10000});return{tabId:t.id,clicked:p.selector};}if(p.action==='fill'){await page.locator(p.selector).fill(p.text,{timeout:10000});return{tabId:t.id,filled:p.selector};}throw Error('Unknown browser action');}
 chatIntent(){this.inputIntent='chat';}
 guardFocus(t){try{if(!t||this.inputIntent===t.id)return false;if(!this.win||this.win.isDestroyed()||!this.win.isFocused())return false;const wc=this.win.webContents;if(wc.isDestroyed())return false;setTimeout(()=>{try{if(this.inputIntent!==t.id&&!this.win.isDestroyed()&&this.win.isFocused()&&!wc.isDestroyed())wc.focus();}catch{}},0);return true;}catch{return false;}}
 dispose(){for(const v of this.views.values())if(!v.webContents.isDestroyed())v.webContents.close();this.views.clear();}
}
module.exports={Browser};
