const fs=require('fs'),path=require('path'),{execFileSync}=require('child_process');
const root=path.resolve(__dirname,'..'),assets=path.join(root,'assets'),sharp=require('../runtime/node_modules/sharp');
const theme=require('../assets/logo.json'),master=fs.readFileSync(path.join(assets,'logo-master.svg'),'utf8');
const symbol=master.replaceAll('currentColor',theme.accentDark),inner=symbol.replace(/<svg[^>]*>/,'').replace('</svg>','');
const lockup=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 148 24"><svg width="24" height="24" viewBox="0 0 64 64">${inner}</svg><text x="31" y="16.5" fill="#ffffff" font-family="-apple-system,BlinkMacSystemFont,sans-serif" font-size="13" font-weight="500" letter-spacing=".3">NODO</text><rect x="78.5" y="2" width="69" height="20" rx="5" fill="none" stroke="#ffffff" stroke-width="1"/><text x="113" y="16.5" fill="#ffffff" text-anchor="middle" font-family="-apple-system,BlinkMacSystemFont,sans-serif" font-size="13" font-weight="500">HARNESS</text></svg>`;
for(const [f,s]of [['nodo-symbol.svg',symbol],['nodo-lockup.svg',lockup]]){fs.writeFileSync(path.join(assets,f),s);fs.writeFileSync(path.join(root,'ui',f),s);}
let client=fs.readFileSync(path.join(root,'extension/client.js'),'utf8');const uri=s=>'data:image/svg+xml;base64,'+Buffer.from(s).toString('base64');
client=client.replace(/\/\*NODO_LOCKUP_START\*\/[\s\S]*?\/\*NODO_LOCKUP_END\*\//,`/*NODO_LOCKUP_START*/ const brand=()=>h('img',{src:${JSON.stringify(uri(lockup))},width:148,height:24,alt:'NODO HARNESS',className:'nodo-brand',style:{display:'block'}}); /*NODO_LOCKUP_END*/`);
client=client.replace(/const mark=\(\{size=24\}\)=>h\('img',\{src:(?:'[^']+'|"[^"]+")/,`const mark=({size=24})=>h('img',{src:${JSON.stringify(uri(symbol))}`);
fs.writeFileSync(path.join(root,'extension/client.js'),client);
const version=require('../package.json').version;
for(const f of ['index.html','about.html']){const p=path.join(root,'ui',f);fs.writeFileSync(p,fs.readFileSync(p,'utf8').replace('width="192"','width="148"').replace(/Version \d+\.\d+\.\d+(?: RC)?/g,'Version '+version).replaceAll('#1b1b1b',theme.background));}
const icon=Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024"><rect x="48" y="48" width="928" height="928" rx="210" fill="${theme.background}"/><g transform="translate(128 128) scale(12)">${inner}</g></svg>`);
(async()=>{const out=path.join(assets,'NODO.iconset');fs.mkdirSync(out,{recursive:true});for(const size of [16,32,128,256,512])for(const scale of [1,2])await sharp(icon).resize(size*scale).png().toFile(path.join(out,`icon_${size}x${size}${scale===2?'@2x':''}.png`));for(const size of [16,32,64])await sharp(Buffer.from(symbol)).resize(size).png().toFile(path.join(assets,`nodo-symbol-${size}.png`));execFileSync('/usr/bin/iconutil',['-c','icns',out,'-o',path.join(assets,'NODO.icns')]);console.log('One master logo -> lockup, app icon and sizes');})().catch(e=>{console.error(e.message);process.exitCode=1;});
